name: Playground Comment

on:
  pull_request:

jobs:
  playground:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    env:
      LANDING_PAGE: "/wp-admin/"

    steps:
      - uses: actions/checkout@v4

      # Prepare a folder named exactly like the repo as the plugin root.
      # If the repo already has such a folder (common for WP plugins), use it.
      # Otherwise, stage one and copy root files into it (excluding CI junk).
      - name: Prepare plugin folder
        id: prep
        run: |
          set -euxo pipefail
          REPO="${{ github.event.repository.name }}"
          if [ -d "$REPO" ]; then
            # Plugin already lives in a subfolder named like the repo
            echo "PKG_DIR=$REPO" >> "$GITHUB_OUTPUT"
          else
            # Create a clean staging dir to avoid copying into itself
            STAGE="${REPO}-pkg"
            mkdir -p "$STAGE/$REPO"
            rsync -a \
              --exclude='.git' \
              --exclude='.github' \
              --exclude='node_modules' \
              --exclude="${STAGE}" \
              ./ "$STAGE/$REPO/"
            echo "PKG_DIR=$STAGE/$REPO" >> "$GITHUB_OUTPUT"
          fi

      # Upload the FOLDER (not a .zip). The artifact service zips it for us,
      # keeping the top-level folder name inside the archive.
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ steps.prep.outputs.PKG_DIR }}
          # Optional: faster uploads for already-compressed assets
          compression-level: 0

      # Comment with a Playground link that installs from the artifact ZIP
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Test on Playground**
            [Test this pull request on the Playground](https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fprogressplanner.com%2Fresearch%2Fblueprint-pp.php%3Frepo%3D${{ github.repository }}%26branch%3D${{ github.head_ref }})
            or [download the zip](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/${{ github.event.repository.name }}.zip)
