name: Progress Planner Playwright Tests

env:
  WP_BASE_URL: http://localhost:8080
  WP_ADMIN_USER: admin
  WP_ADMIN_PASSWORD: password
  WP_ADMIN_EMAIL: admin@example.com
  WP_DB_USER: wpuser
  WP_DB_PASSWORD: wppass
  WP_DB_NAME: wordpress

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ${{ env.WP_DB_NAME }}
          MYSQL_USER: ${{ env.WP_DB_USER }}
          MYSQL_PASSWORD: ${{ env.WP_DB_PASSWORD }}
        ports:
          - 3306:3306
      wordpress:
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: ${{ env.WP_DB_USER }}
          WORDPRESS_DB_PASSWORD: ${{ env.WP_DB_PASSWORD }}
          WORDPRESS_DB_NAME: ${{ env.WP_DB_NAME }}
          WORDPRESS_TABLE_PREFIX: wp_
          WORDPRESS_DEBUG: 1
          WORDPRESS_URL: ${{ env.WP_BASE_URL }}
          WORDPRESS_ADMIN_USER: ${{ env.WP_ADMIN_USER }}
          WORDPRESS_ADMIN_PASSWORD: ${{ env.WP_ADMIN_PASSWORD }}
          WORDPRESS_ADMIN_EMAIL: ${{ env.WP_ADMIN_EMAIL }}
        ports:
          - 8080:80
        options: >-
          --health-cmd="curl --silent --fail http://localhost:8080/wp-login.php || exit 0"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js & Playwright
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -D @playwright/test
      - run: npx playwright install --with-deps

      - name: Complete WordPress installation
        run: |
          echo "Installing WordPress at: $WP_URL"
          curl --silent -X POST "$WP_BASE_URL/wp-admin/install.php?step=2" \
          -d "weblog_title=My%20WordPress%20Site" \
          -d "user_name=$WP_ADMIN_USER" \
          -d "admin_password=$WP_ADMIN_PASSWORD" \
          -d "admin_password2=$WP_ADMIN_PASSWORD" \
          -d "admin_email=$WP_ADMIN_EMAIL" \
          -d "public=1"

      - name: Install and activate plugin
        run: |
          # Copy plugin files to WordPress plugins directory
          sudo cp -r . /var/www/html/wp-content/plugins/progress-planner

          # Activate the plugin using WP-CLI
          docker exec $(docker ps -qf "name=wordpress") wp plugin activate progress-planner --allow-root

      # - name: Wait for WordPress to be ready
      #   run: |
      #     echo "Waiting for WordPress to be ready..."
      #     sleep 30  # Adjust if necessary based on the container startup time

      - name: Run Playwright Tests
        run: npx playwright test tests/e2e/

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Playwright screenshots as artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: |
            onboarding-failed.png  # Specify the path of the screenshot you want to upload
