name: Progress Planner Playwright Tests

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wpuser
          MYSQL_PASSWORD: wppass
        ports:
          - 3306:3306
      wordpress:
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: wpuser
          WORDPRESS_DB_PASSWORD: wppass
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_TABLE_PREFIX: wp_
          WORDPRESS_DEBUG: 1
          WORDPRESS_URL: http://localhost:8080
          WORDPRESS_ADMIN_USER: admin
          WORDPRESS_ADMIN_PASSWORD: password
          WORDPRESS_ADMIN_EMAIL: admin@example.com
        ports:
          - 8080:80
        options: >-
          --health-cmd="curl --silent --fail http://localhost:8080/wp-login.php || exit 0"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js & Playwright
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -D @playwright/test
      - run: npx playwright install --with-deps

       # Run WordPress installation if needed
      - name: Complete WordPress installation
        run: |
          if ! curl --silent --fail http://localhost:8888/wp-login.php; then
            curl --silent --data "weblog_title=My%20WordPress%20Site&user_name=${{ secrets.WP_ADMIN_USER }}&admin_password=${{ secrets.WP_ADMIN_PASSWORD }}&admin_password2=${{ secrets.WP_ADMIN_PASSWORD }}&admin_email=${{ secrets.WP_ADMIN_EMAIL }}&submit=Install%20WordPress" http://localhost:8888/wp-admin/install.php
          fi

      # - name: Wait for WordPress to be ready
      #   run: |
      #     echo "Waiting for WordPress to be ready..."
      #     sleep 30  # Adjust if necessary based on the container startup time

      - name: Run Playwright Tests
        run: npx playwright test tests/e2e/
        env:
          WP_ADMIN_USER: admin
          WP_ADMIN_PASSWORD: password
          WP_BASE_URL: http://localhost:8080

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Playwright screenshots as artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: |
            onboarding-failed.png  # Specify the path of the screenshot you want to upload
